# production setup used in tests
replicas: 2

webhooks:
  enabled: true

pdb:
  enabled: true

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app: wave
