name: Run tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
    - README.md
    - LICENSE.md
  push:
    branches:
    - master

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.6'
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: Cache kubebuilder
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace	}}/kubebuilder_2.3.1_linux_amd64
          key: ${{ runner.os }}-build-kubebuilder-2.3.1
      - name: Cache tooling
        uses: actions/cache@v2
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-build-gobin
      - name: Setup test tooling
        run: |
          go get github.com/onsi/ginkgo/ginkgo && go get github.com/onsi/gomega/...
          if ! [[ -x $(go env GOPATH)/bin/golangci-lint ]]; then curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0; fi
          if ! [[ -d ~/kubebuilder_2.3.1_linux_amd64 ]]; then curl -sSfL https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_linux_amd64.tar.gz | tar zxvf -; fi
          if ! [[ -x $(go env GOPATH)/bin/dep ]]; then curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh; fi
          GO111MODULE=on go get sigs.k8s.io/kustomize/kustomize/v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ./src/github.com/${{ github.repository }}/vendor
          key: ${{ runner.os }}-build-depcache-${{ hashFiles('**/Gopkg.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-depcache-
      - name: Download dependencies
        run: |
          export GOPATH=$(go env GOPATH):$(pwd)
          cd ./src/github.com/${{ github.repository }}
          dep ensure --vendor-only
      - name: Configure
        run: |
          export GOPATH=$(go env GOPATH)
          export PATH=$GOPATH/bin:$PATH
          ./configure --with-kubebuilder=${{ github.workspace	}}/kubebuilder_2.3.1_linux_amd64/bin --with-kubectl=${{ github.workspace	}}/kubebuilder_2.3.1_linux_amd64/bin/kubectl
        working-directory: ./src/github.com/${{ github.repository }}
      - name: Run Tests
        run: |
          export GOPATH=$(go env GOPATH):$(pwd)
          cd ./src/github.com/${{ github.repository }}
          make check
